### PR TITLE
Agnostic communication protocol

### PR DESCRIPTION
**Pull request by albfan**
To test "dominant axis" https://github.com/FreeSpacenav/spacenavd/pull/65

I port this to support wayland.

This comes from https://github.com/FreeSpacenav/libspnav/pull/8, but rebasing latest changes and making the example smart enough to configure itself.

kudos to @Arxcis

### CODE REVIEW

**Comment by albfan** [comment]
I don't know much about x11 so is kind of a mystery with XPending is needed on wayland, but I think the general idea is clear:

- find if you're on X11 or wayland
- handle events depending on that

If this PR makes sense I can rework any part that needs changes, as said, don't have much experience on wayland or x11

**Comment by albfan** [comment]
NOTE: Using disable rotation and disable translation on buttons, we loose the reset behaviour.

Maybe a key like "r" could reset the cube

**Comment by albfan** [comment]
Checking simple example, it includes 

    #if defined(BUILD_AF_UNIX)  

so I'm unsure now what is the best approach.

**Comment by jtsiomb** [comment]
The cube example demonstrates how to use the X11 protocol. There are other examples which demonstrate using the UNIX domain socket protocol. There's no reason to make the cube example more complicated to show both.

If you want to modify it to use it for testing your dominant axis feature, by all means do so, but there's no reason to merge the modified version back to libspnav.

**Pull request closed without merging**
