### PR TITLE
Add support for 'dev' index (from /dev/input/eventN)

### PR DESCRIPTION
**Pull request by tomlankhorst**
Corresponds to https://github.com/FreeSpacenav/spacenavd/issues/13
and https://github.com/FreeSpacenav/spacenavd/pull/14.

### CODE REVIEW

**Comment by jtsiomb** [comment]
See the spacenavd pull request about breaking changes to the protocol. Also, this project uses C89. Changing it to C11 just to use a anonymous structure is not acceptable.

**Comment by tomlankhorst** [comment]
I understand that you're not willing to merge this due to breaking changes. For the time being, people that want multi-dev support could use my fork.

**Comment by eMPee584** [comment]
.. so without the anonymous structure, this could go into a 0.7 release? :cowboy_hat_face:

**Comment by jtsiomb** [comment]
No, it breaks the protocol, and breaks binary compatibility. A new protocol is necessary for this and a number of other useful features. And a mechanism to maintain backwards compatibility by falling back to the old protocol with reduced functionality on both sides (spacenavd and libspnav).

**Pull request closed without merging**
